### ISSUE TITLE
Trying to get the info from modbus registers directly

### ISSUE THREAD

**Issue by Arise** [wimb0/home-assistant-saj-r5-modbus#102]
@wimb0 I went ahead and was trying to get the info directly from HA modbus integration, I settled for a test file like this:
```

- name: modbus_saj
  type: tcp
  host: 192.168.100.34
  port: 8899
  message_wait_milliseconds: 1000
  timeout: 5
  delay: 3
  sensors:
    # realtime_data = self._read_holding_registers(unit=1, address=0x100, count=???) #256
    - name: modbus_register_block_info
      slave: 1
      address: 256
      count: 22
      data_type: custom
      #            H                                    mpvmode - decode_16bit_uint 
      #             III                                 faultMsg0,faultMsg1,faultMsg2  -  3 x decoder.decode_32bit_uint
      #                HHH                              pv1volt, pv1curr, pv1power  - 3 x decode_16bit_uint
      #                   HHH                           pv2volt, pv2curr, pv2power  - 3 x decode_16bit_uint
      #                      HHH                        pv3volt, pv3curr, pv3power  - 3 x decode_16bit_uint
      #                         H - busvolt
      #                          h - invtempc
      #                           h - gfci
      #                            H - power            Active power of inverter total output
      #                             h - qpower          Reactive power of invertertotal output
      #                              h - pf             Total power factor of inverter
      structure: ">HIIIHHHHHHHHHHhhHhh"
      scan_interval: 5

    # realtime_data = self._read_holding_registers(unit=1, address=0x116, count=???) #278
    - name: modbus_register_block_lines
      slave: 1
      address: 278
      count: 18
      data_type: custom
      #                               HHHhHh -l1volt, l1curr, l1freq, l1dci, l1power, l1pf
      #                                     HHHhHh -l2volt, l2curr, l2freq, l2dci, l2power, l2pf
      #                                           HHHhHh -l3volt, l3curr, l3freq, l3dci, l3power, l3pf
      structure:                    ">HHHhHhHHHhHhHHHhHh"
      scan_interval: 5
      
    # realtime_data = self._read_holding_registers(unit=1, address=0x128, count=???) #296
    - name: modbus_register_block_statistics
      slave: 1
      address: 296
      count: 14
      data_type: custom
      #                               HHHH iso1,iso2,iso3,iso4
      #                                   H todayenergy decode_16bit_uint
      #                                    I monthenergy decode_32bit_uint
      #                                     I yearenergy decode_32bit_uint
      #                                      I totalenergy decode_32bit_uint
      #                                       H    todayhour
      #                                        h   totalhour
      #                                         H  errorcount
      structure:                    ">HHHHHIIIHhH"
      scan_interval: 5  
```

the problem I'm encountering is that I had to split the multiple registers block in maybe 2 or 3 blocks (modbus_register_block_info, modbus_register_block_lines and modbus_register_block_statistics). If I try to read everything in a single block i get an error/unknown, whatever, any idea why this might not work?
